on: [pull_request_target]
name: Auto-Merge Bot
jobs:
#   auto_merge_bot:
#     runs-on: ubuntu-latest
#     name: EIP Auto-Merge Bot
#     if: github.event.pull_request.draft == false
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node.js Environment
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: auto-merge-bot
#         uses: ethereum/EIP-Bot@43353a55352c242b5fd1b15093b5fc188385a8e1 # master
#         id: auto-merge-bot
#         with:
#           GITHUB-TOKEN: ${{ secrets.TOKEN }} 
#           MERGE_ENABLED: false
#           CORE_EDITORS: "@MicahZoltu,@lightclient,@axic,@gcolvin"
#           ERC_EDITORS: "@lightclient,@axic"
#           NETWORKING_EDITORS: "@MicahZoltu,@lightclient,@axic"
#           INTERFACE_EDITORS: "@lightclient,@axic"
#           META_EDITORS: "@lightclient,@axic,@gcolvin"
#           INFORMATIONAL_EDITORS: "@lightclient,@axic,@gcolvin"
#   enable-auto-merge:
# #     if: github.repository == 'ethereum/eips'
#     runs-on: ubuntu-latest
# #     needs: ["auto_merge_bot"]
#     steps:
#     - name: Enable Automerge
#       run: gh pr merge --auto --merge "$PR_URL"
#       env:
#         PR_URL: ${{github.event.pull_request.html_url}}
#         GITHUB_TOKEN: ${{secrets.TOKEN}}     
    addLabel:
      runs-on: ubuntu-latest
      steps:
      - name: Add Label
        uses: "alita-moore/add-pr-label@1.0.1"
        env:
            githubToken: "${{ secrets.GITHUB_TOKEN }}"
            labelToAdd: "automerge"
          
#   enable-auto-merge2:
#     runs-on: ubuntu-latest
#     needs: ["enable-auto-merge"]
#     if: always() && needs.enable-auto-merge.result == 'failure'
#     steps:
#     - name: Enable Automerge V2
#       uses: "pascalgn/automerge-action@v0.14.3"
#       env:
#           GITHUB_TOKEN: "${{ secrets.TOKEN }}"
