on: [issues]

jobs:
  create_comment:
      runs-on: ubuntu-latest
      steps:
      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            testing
