name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: exit 1
      
